pokt-foundation/docs

- resources/references/supported-blockchains.md
- xDai archival
- Algorand & archival
- Arweave
> Adding new chains

- pokt-accounts-and-transactions/transaction-construction-and-offline-signature.md
It required some changes due to being wrong in certain things & additional PocketJS features.
> Improve offline transaction signing docs

- v1/utility.md
Proposing to include an Incentives diagram for V1.0 Quality Based Servicer Rewards
> Git-Book - V1.0 Utility - Incentives - Quality Based

- resources/public-rpc-endpoints/dfk-chain-metamask.md
Now includes both Chainlist and manual setup.
> Adds more details on DFK Chain MetaMask setup

- paths/node-runner/zero-to-node/1-2-configure-dns.md
- paths/node-runner/zero-to-node/1-3-ssh-login.md
- paths/node-runner/zero-to-node/1-4-set-hostname.md
- paths/node-runner/zero-to-node/1-5-create-user.md
- paths/node-runner/zero-to-node/2-2-install-go.md
- paths/node-runner/zero-to-node/4-4-nginx-config.md
> Zero to node staging - fix formatting issues

- paths/node-runner/zero-to-node/4-1-snapshot-download.md
- paths/node-runner/zero-to-node/5-2-staking.md
Update staking command for RC-0.8.2
> update zero-to-node staking syntax

- node/tutorials/zero-to-node/pocket-config.md
fix broken link to supported-chains.md
> fix broken link to supported-chains.md

- learn/vision.md
This content was removed during the recent refactoring, but is restored here with some slight alterations in copy.
> Adds Product Comparison section back in

- supported-blockchains.md
- use/public-rpc/README.md
This will result in a list of all the Public RPC endpoints for every chain that Pocket Network supports.
> Refactoring Public RPC listing

- content/learn/protocol/security.md
- content/use/get-endpoint.md
> Fix: Minor typo

- content/learn/economics/nodes.md
Change: 25 blocks per session to 4 blocks per session
> Typo with how frequent a session is

- content/learn/economics/nodes.md
this paragraph is a bit confusing due to historical context. I added a hyperlink to FAQ page, considering this reading material is a precursor before you head to FAQ page.
> add hyperlink to pip-22 strategy

- content/node/environment.md
Updated 200GB to 500GB for hardware requirements.
> Update disk requirements

- content/node/tutorials/zero-to-node/going-live.md
- content/node/tutorials/zero-to-node/pocket-config.md
- content/node/tutorials/zero-to-node/proxy-config.md
- content/node/tutorials/zero-to-node/server-setup.md
- content/node/tutorials/zero-to-node/software-install.md
* Downloads snapshot sooner, and through screen
* Adds secondary storage volume, and moves user directory to that volume
* Adds some command responses for easier verification
* Updates version numbers and size requirements
> Updates and refinements to Zero To Node tutorial

- content/node/environment.md
- content/node/setup.md
- content/node/update.md
Also separates out the update (upgrade) section into its own page.
> Update and reorganize node setup docs

- .gitignore
- content/_index.md
- content/pokt/wallets.md
- layouts/shortcodes/video.html
- update some links. 
- update wallet with unstoppable domains content.
> Unstoppable Domains

- content/supported-blockchains/_index.md
add celo, velas, and velas archival to supported chains
Link T-19287
> Update Support Blockcahins

- content/api-docs/bnb-smart-chain-evm.md
- content/supported-blockchains/_index.md
- content/use/public-rpc/_index.md
- content/use/public-rpc/bsc.md
- data/chains.yaml
Update binance smart chain to bnb smart chain
Link T-19400
> Update binance smart chain to bnb smart chain

- content/supported-blockchains/_index.md
Remove bsc-archival public rpc
> Remove bsc-archival public rpc

- content/use/public-rpc/_index.md
Added Kava Mainnet and Oasys Mainnet to the public rpc table.
> feat: added kava mainnet and oasys mainnet

- content/supported-blockchains/_index.md
* Remove Algo
* Remove duplicated DFK
* Remove Avax CRA
* Move Gnosis Mainnet above Gnosis Archival
> Fix Supported Blockchains

- content/learn/glossary.md
- content/pokt/_index.md
> Dr link updates

- content/pokt/wallets.md
- content/pokt/wpokt/_index.md
- content/pokt/wpokt/bridging.md
Updated links to wallets, cleaned up some documentation, fixed missing info.
> Wpokt updates

- content/pokt/wpokt/bridging.md
> Update bridging.md with NodeWallet

- content/pokt/wallets.md
- content/pokt/wpokt/bridging.md
Addresses inconsistencies and clarifies some timing around wrapping pokt
> 04102023 docs updates

- content/use/public-rpc/_index.md
- content/use/public-rpc/replace-endpoint.md
- layouts/shortcodes/loom.html
This PR encompasses several updates to the POKT Network endpoint configuration documentation to ensure users have the most accurate and up-to-date information. Below are the key updates included in this PR:
1. **Endpoint Table Update:**
- Replaced the previous RPC URLs with the new endpoints in the endpoints table.
- Reformatted the endpoints table for better readability and narrowness, ensuring a clean display of information.
2. **Video Embed:**
- Added a new shortcode component to support Loom video embedding.
- Updated the video tutorial with a new Loom video link.
3. **New Styled Table Shortcode:**
- Created a new shortcode for styled tables to ensure consistent formatting across the documentation.
4. **Directory Structure Update:**
- Removed old subdirectories that were no longer …
> Update POKT Endpoint Configuration Documentation
